### ISSUE TITLE
Update to Intellij 2019.3

### ISSUE THREAD

**Issue by kid2407** [knoxfighter/intellij-factorio-autocompletion#1]
Currently, Intellij refuses to let me install this plugin because it was build for version `192.*`. Since The 2019.3 builds use the build numbers `193.*`, i can't load the plugin.
It would be nice to have compatibility with the most recent version :)

**Comment by knoxfighter** [comment]
Yes, that is true, i also wish to use 2019.3. This plugin is based on [EmmyLua](https://github.com/EmmyLua/IntelliJ-EmmyLua), so i have to wait until emmyLua is updated before i can update :(

**Comment by kid2407** [comment]
@knoxfighter There it is :D https://github.com/EmmyLua/IntelliJ-EmmyLua/releases/tag/1.3.1

**Comment by knoxfighter** [comment]
Yes, the update is pending jetbrains approval. Every update, a jetbrains employe has to look over the plugin and automatic tests will be run. The approval normally takes up to two workdays :)

After it is approved, i can update my code and then submit my update. My update approval will again take around two workdays.

**Comment by knoxfighter** [comment]
I've updated and today the new version got verified and is now available in the plugins repository. Also a few new things where added in the version :)
When any error occurres, just report them and i will fix them^^
