### ISSUE TITLE
Add support for the global "defines"

### ISSUE THREAD

**Issue by kid2407** [knoxfighter/intellij-factorio-autocompletion#2]
When registering an event, you usually make use of the global `defines` variable like in the following example:
```
script.on_event(defines.events.on_tick, function (event)
    -- Do stuff
end)
```
For this use case, I'd like to have autocompletion for the `defines` variable, the same as it already exists for `script`, `game` etc.

**Comment by knoxfighter** [comment]
That is an error on my side, the defines table is crawled and added to the files, that are included ... but they are defined local, so no autocompletion is done :(

I will fix that and release a new version, will be approved in a few days.

**Comment by knoxfighter** [comment]
Version 1.2.1 got approved and is available to download from the plugin repository :)
