### ISSUE TITLE
Version 2020.x.x incompatibility

### ISSUE THREAD

**Issue by Varatnar** [knoxfighter/intellij-factorio-autocompletion#5]
Seems to be incompatible with newer platform version 2020.x.x

(Emmy lua has been updated as of this issue creation)

**Comment by knoxfighter** [comment]
EmmyLuas update got approved yesterday. I updated my code and uploaded the new version. It will be approved in a few days :)

**Comment by knoxfighter** [comment]
ok, never mind, they already approved it xD
Update is available in the repository.

**Comment by Varatnar** [comment]
That was fast, thanks !
